/*
   index.tsx
   home page of web app
*/

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

/*
   Home
   homepage paage jfx function to display home page
*/
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MOB system</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main className="grid h-screen place-items-center">
        <div className="flex flex-col justify-center content-center">
          <p className="">MOB is a authentication system that identifies existing users faces usingthe eigenface algorithm.</p>
          <Link href={"/login"} className="btn btn-primary w-24">Login</Link>
        </div>
     </main>
    </>
  );
};

export default Home;




