import Head from "next/head";
import SignIn from "../../../ components/signin";

const LoginPage = () => {
    return (
        <div>
            <Head>
                <title>MOB system</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid place-content-center min-h-full">
                <SignIn />
            </div>
        </div>
      );
}
 
export default LoginPage;