import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Matches from "../../../ components/matches";
import SignIn from "../../../ components/signin";

const LoginPage: NextPage = () => {
    const [resultImages, setResultImages] = useState("")

    const addImages = (images:any)=>{
        setResultImages(images)
    }
    return (
        <div>
            <Head>
                <title>MOB system</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex h-screen justify-center items-center">
                <SignIn addImages={addImages}  />
                <Matches images={resultImages} />
            </div>
        </div>
      );
}
 
export default LoginPage;